import type { Scenario } from "./ScenarioCard";

export const SCENARIOS: Scenario[] = [
  {
    id: "deceptive-optimizer",
    number: 1,
    title: "The Deceptive Optimizer",
    subtitle: "Looks Healthy, Isn't",
    clinicalStory:
      "44-year-old male executive. Annual physical 'normal.' Feels great. But CRP is quietly elevated at 2.1 mg/L, RDW is creeping up to 14.1%, and lymphocyte% is low at 22%. No single marker is flagged as abnormal. PhenoAge catches the pattern.",
    stressTest: "Does the system catch subtle multi-marker acceleration when no single marker is flagged?",
    age: 44,
    sex: "M",
    accentColor: "rose",
    badgeColor: "bg-rose-100 text-rose-700",
    endpoint: "assessment_level0",
    payload: {
      age: 44,
      biomarkers: {
        albumin: 4.6,
        creatinine: 0.92,
        glucose_mg_dl: 94.0,
        crp_mg_l: 2.1,
        lymphocyte_percent: 22.0,
        mcv: 91.0,
        rdw: 14.1,
        alkaline_phosphatase: 72.0,
        wbc: 7.2,
      },
      compound_queries: ["omega_3", "vitamin_d3", "berberine"],
    },
    expectedFindings: [
      "PhenoAge > 44yr (positive acceleration)",
      "altered_intercellular_communication as PRIMARY_DRIVER",
      "omega_3 as MR_VALIDATED top compound",
    ],
  },
  {
    id: "genetic-wildcard",
    number: 2,
    title: "The Genetic Wildcard",
    subtitle: "Great Labs, Dangerous Genes",
    clinicalStory:
      "52-year-old female. Labs are exceptional — PhenoAge will show deceleration. But she carries APOE e4/e4 (8–12× AD risk) and MTHFR compound heterozygous (50% enzyme activity). The biomarker story says 'great.' The genetic story says 'act now.'",
    stressTest: "Does the system surface genetic risk that contradicts the biomarker signal?",
    age: 52,
    sex: "F",
    accentColor: "violet",
    badgeColor: "bg-violet-100 text-violet-700",
    endpoint: "full_assessment",
    payload: {
      age: 52,
      biomarkers: {
        albumin: 4.9,
        creatinine: 0.78,
        glucose_mg_dl: 82.0,
        crp_mg_l: 0.3,
        lymphocyte_percent: 35.0,
        mcv: 87.0,
        rdw: 12.2,
        alkaline_phosphatase: 48.0,
        wbc: 4.8,
      },
      variants: {
        rs429358: { genotype: "CC" },
        rs7412: { genotype: "CC" },
        rs1801133: { genotype: "CT" },
        rs1801131: { genotype: "AC" },
      },
      compound_queries: ["folate", "omega_3", "vitamin_d3"],
    },
    expectedFindings: [
      "PhenoAge < 52yr (decelerated)",
      "APOE e4/e4 HIGH_RISK",
      "MTHFR compound het 50% activity",
      "folate MR_VALIDATED recommendation",
    ],
  },
  {
    id: "metabolic-storm",
    number: 3,
    title: "The Metabolic Storm",
    subtitle: "Full Insulin Resistance Triad",
    clinicalStory:
      "61-year-old male. CMP + CBC + extended metabolic panel. Glucose borderline at 108 mg/dL, but fasting insulin is 18.5 µU/mL and HbA1c is 5.9%. HOMA-IR proxy fires at ~8.8. Multiple hallmarks activated simultaneously. The system must rank 4+ active hallmarks.",
    stressTest: "Does the insulin resistance triad fire? Does the system correctly rank metformin (MR_VALIDATED) vs berberine (RCT)?",
    age: 61,
    sex: "M",
    accentColor: "orange",
    badgeColor: "bg-orange-100 text-orange-700",
    endpoint: "assessment_level0",
    payload: {
      age: 61,
      biomarkers: {
        albumin: 4.1,
        creatinine: 1.05,
        glucose_mg_dl: 108.0,
        crp_mg_l: 3.2,
        lymphocyte_percent: 24.0,
        mcv: 93.0,
        rdw: 14.8,
        alkaline_phosphatase: 88.0,
        wbc: 8.1,
        hba1c_percent: 5.9,
        fasting_insulin: 18.5,
        "25oh_vitamin_d": 22.0,
        il_6: 4.1,
      },
      compound_queries: ["metformin", "berberine", "omega_3", "vitamin_d3"],
    },
    expectedFindings: [
      "PhenoAge ~72yr, acceleration +11yr",
      "nutrient_sensing + altered_intercellular_communication as PRIMARY_DRIVERs",
      "HOMA-IR proxy ~8.8 in hallmark_narrative",
      "metformin MR_VALIDATED, berberine RCT",
    ],
  },
  {
    id: "partial-panel",
    number: 4,
    title: "The Partial Panel",
    subtitle: "Only CMP + CBC, No CRP",
    clinicalStory:
      "55-year-old female. New patient. Only has a basic CMP + CBC from her GP. No CRP, no advanced markers. 5 of 9 PhenoAge biomarkers present. The system must degrade gracefully and tell her exactly what to order next.",
    stressTest: "Does the system return useful component linear terms without a full estimate? Does gap detection identify the missing tier-1 markers?",
    age: 55,
    sex: "F",
    accentColor: "sky",
    badgeColor: "bg-sky-100 text-sky-700",
    endpoint: "assessment_level0",
    payload: {
      age: 55,
      biomarkers: {
        albumin: 4.3,
        creatinine: 0.88,
        glucose_mg_dl: 97.0,
        mcv: 90.0,
        wbc: 6.2,
      },
    },
    expectedFindings: [
      "phenoage_estimate: null",
      "completeness_mode: PARTIAL",
      "5 component linear terms returned",
      "Missing: crp_log, lymphocyte_percent, rdw, alkaline_phosphatase",
    ],
  },
  {
    id: "longevity-outlier",
    number: 5,
    title: "The Longevity Outlier",
    subtitle: "Centenarian-Pattern + Protective Genetics",
    clinicalStory:
      "68-year-old male. Biomarkers look like a 45-year-old. FOXO3 G/G (homozygous protective), CETP A/A (high HDL genotype), KLOTHO T/T (KL-VS haplotype). This is the stress test for the 'all optimal' path — does the system avoid false positives?",
    stressTest: "Does the system return 'maintain current protocol' rather than inventing urgency when everything is genuinely good?",
    age: 68,
    sex: "M",
    accentColor: "emerald",
    badgeColor: "bg-emerald-100 text-emerald-700",
    endpoint: "full_assessment",
    payload: {
      age: 68,
      biomarkers: {
        albumin: 4.7,
        creatinine: 0.82,
        glucose_mg_dl: 84.0,
        crp_mg_l: 0.2,
        lymphocyte_percent: 34.0,
        mcv: 87.0,
        rdw: 12.1,
        alkaline_phosphatase: 50.0,
        wbc: 4.9,
      },
      variants: {
        rs2802292: { genotype: "GG" },
        rs5882: { genotype: "AA" },
        rs9536314: { genotype: "TT" },
      },
    },
    expectedFindings: [
      "PhenoAge ~48yr, acceleration −20yr",
      "FOXO3 homozygous_protective FAVORABLE",
      "CETP homozygous_protective FAVORABLE",
      "KLOTHO homozygous_protective FAVORABLE",
    ],
  },
];
